# sudo: false

language: 
 - cpp

compiler:
  - gcc

os: linux

dist: trusty

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      


# Change this to your needs
# script: ./configure &amp;&amp; make

before_install:
  - pip install --user cpp-coveralls

before_script: 
  - cd cpp_project/compile-skills/scons-demo/

script: 
#scons-demo
  - scons
#gtest-demo
  - cd ..
  - mkdir build
  - cd build
  - cmake ..
  - make
  - ./unit_tests

after_script:
  - ./hello

after_success:
  - coveralls --root .. -E ".*external.*" -E ".*CMakeFiles.*" -E ".*test/.*.cpp.*"

branches:
  only:
    - master

notifications:
  recipients:
    - mikosong2013@gmail.com
  email:
    on_success: never
    on_failure: change
